services:
  - type: web
    plan: free
    name: BDNetwork
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/AxomLegend/TG-FileStore.git      
    branch: main
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        synv: false 
      - key: DB_CHANNEL 
        sync: false
      - key: BOT_OWNER
        sync: false
      - key: DATABASE_URL 
        sync: false 
      - key: UPDATES_CHANNEL 
        sync: false
      - key: LOG_CHANNEL 
        sync: false    
    autoDeploy: false 
